### ISSUE TITLE
Location Address not accurate 

### ISSUE THREAD

**Issue by iHaiderAli** [kingsammalik/SamLocationAndGeocoding#6]
I have integrated and getting user current location but this library not giving the accurate latitude and longitude or building address.
Please try to update me asap.

**Comment by kingsammalik** [comment]
Please ensure that your gps is turned on before executing the library. Let me know if you face any issues then.

**Comment by kingsammalik** [comment]
Hi, I have rolled out the new version of the library, I believe this will solve your problem.

**Comment by iHaiderAli** [comment]
Thank you
